roihunter/gold-digger

gold_digger/config/params.py

http://is.roihunter.com/issues/11903
@miso-belica I was unable to find who is requesting "SSK" currency data. I only found that fishy has old data too. Check [this](https://github.com/business-factory/fish-parser/blob/dev/fishy/utils/currency.py#L168) and there are more currencies which are no longer supported by Facebook according to [this page](https://developers.facebook.com/docs/marketing-api/currencies). I think, I should remove them from there.
@business-factory/pythonistas Please review and merge.

Removed SKK currency support.  #11903

---

gold_digger/data_providers/google.py

You can receive a response from the old URL containing all HTML tags except for the result.  So tricky from Google. Replacing `www` with `finance` solves the issue.

Fix Google provider URL

---

gold_digger/config/di.py
gold_digger/data_providers/_provider.py
gold_digger/data_providers/currency_layer.py
gold_digger/data_providers/fixer.py
gold_digger/data_providers/google.py
gold_digger/data_providers/grandtrunk.py
gold_digger/data_providers/yahoo.py
gold_digger/managers/exchange_rate_manager.py
tests/test_exchange_rate_manager.py

https://is.roihunter.com/issues/18081
If a specific exchange rate miss from a provider, the provider is requested for the rate. But if the provider does not support rates for such currency, it will always fail and the process will be again repeated. We should find out what currencies are supported by which providers and we should avoid making of useless requests.

Don't request unsupported rates from providers #18081

---

Dockerfile
supervisord.conf

This PR will turn off the old system cron.
Old system cron in old Docker container will be replaced by new python-cron in separated container.
@business-factory/pythonistas Please review and merge

Do not run DB update by cron

---

gold_digger/data_providers/fixer.py
gold_digger/managers/exchange_rate_manager.py

It's sad, but we managed to exceed our monthly limit in a single day
and now we receive "usage_limit_reached" which should be handled properly.
https://logs.roihunter.com/messages/graylog2_1475/8b096262-ab0e-11e8-b72e-002590aa2115
https://logs.roihunter.com/messages/graylog2_1475/76be6d41-ab1e-11e8-b72e-002590aa2115

Fix Fixer - handle error in the response

---

Pipfile
Pipfile.lock
kubernetes/gold-digger-cron-deployment.yaml

@martinvy I locked versions of cron-related packages to the versions they had had before we swiched to pipenv. I briefly checked changelogs of the libraries and I don't think that the error was caused by the new versions, but locking them to the old ones doesn't bring any harm, so prm :)
Edit: `click` locker to `6.2`, cron container memory limit raised to 128Mi

Lock cron packages to specific versions

---

gold_digger/data_providers/grandtrunk.py

This will fix errors messages from [logs](https://logs.roihunter.com/streams/56c6fa73e4b086ef4a3a7fca/search?rangetype=relative&fields=message%2Csource&width=1920&highlightMessage=&relative=432000&q=level%3A3+AND+%22grandtrunk%22).
GrandTrunk provides API of supported currencies by date. We was sending queries for all currencies even they don't exist or are no longer supported. 
Endpoint looks like:
```
http://currencies.apps.grandtrunk.net/currencies[/<date>]
```
> List of all supported currency codes, one per line. If <date> is provided, all supported currencies for that date are listed; when date is omitted all currencies are returned for which the rate on at least one date is known.
Source: http://currencies.apps.grandtrunk.net/
@business-factory/pythonistas

Fixes GrandTrunk provider

---

Pipfile
Pipfile.lock

PyYaml is used by `py-watch` package. Not sure if somebody of you guys uses it but I decided to remove `py-watch` since it's not possible to install it's a pre-release dependency (`PyYaml`). Currently, it's just possible to install prereleases globally. You cannot specify install prerelease just for one package. 
https://is.roihunter.com/issues/27360
@business-factory/pythonistas

Remove `py-watch` package, #27360

---

gold_digger/data_providers/rates_api.py

Prevent doing too many requests to the provider.

Cache supported currencies of Rates API provider.

---

Pipfile
Pipfile.lock
gold_digger/data_providers/_provider.py
gold_digger/data_providers/currency_layer.py
gold_digger/data_providers/fixer.py
gold_digger/data_providers/grandtrunk.py
gold_digger/data_providers/rates_api.py

Cache key for lru_cache is computed also from logger and changes with flow ID.

FIX: Use cachetools instead of lru_cache

---

gold_digger/data_providers/rates_api.py

I noticed that Graylog can't serialize `datetime.date` passed in `date` field, so I checked in this project and found it. :-)
https://logs.roihunter.com/system/indices/failures

FIX: serialize datetime.date to string in logs

---

gold_digger/data_providers/_provider.py
gold_digger/data_providers/currency_layer.py
gold_digger/data_providers/fixer.py
gold_digger/managers/exchange_rate_manager.py
tests/data_providers/conftest.py
tests/data_providers/test_currency_layer.py
tests/data_providers/test_fixer.py
tests/test_exchange_rate_manager.py

https://is.roihunter.com/issues/28707
All providers:
If there are rates unavailable for current day for some provider, use rates from previous day for this provider. In case there are no rates even for previous day, request API.
Fixer:
There is 1000 requests per month usage limit and when this limit was reached, we still made pointless requests to the API. Now, when the API responses with `error 104`, flag is set and all upcoming requests are blocked until the first day of the next month. From outside of the provider it looks like there are no supported currencies and no rates available.
Currency layer:
There is the same requests monthly limit as with Fixer. The same changes were made.

Avoid doing too many requests to Fixer provider #28707

---

gold_digger/data_providers/_provider.py
gold_digger/data_providers/currency_layer.py
gold_digger/data_providers/fixer.py
gold_digger/data_providers/grandtrunk.py
gold_digger/data_providers/rates_api.py
gold_digger/data_providers/yahoo.py
gold_digger/managers/exchange_rate_manager.py
tests/test_exchange_rate_manager.py

https://roihunter.atlassian.net/browse/RH-29401
Few providers have a limit on requests made per month. From those providers we shouldn't request historical rates if we don't have them in database.
In logs I found several cases when requests day by day for the whole year (or even longer) were made and for most of the days we didn't have the rates. It made almost 500 requests in 5 minutes which is half of the limit for Fixer.io and 2x the limit for CurrencyLayer.
If the requests for our API come day by day we cannot distinguish if it is single day or 500 of them. For most of the days we should have data in db and if not, there are other providers we use which don't have these limits and the request can be made.

RH-29401: Further decrease number of requests made

---

Pipfile
Pipfile.lock
setup.cfg
tests/conftest.py
tests/database/__init__.py
tests/database/test_dao.py

- Bump sqlalchemy-utils from 0.33.11 to 0.34.0
- Fixes tests
- Register slow marker

Dev to Master

---

jenkins/pipeline/deploy-master.groovy

I had an incident where Shortener master was not rolled out, probably because of the piped commands. I want to try something else.

Use in-place sed command during deploy

---

README.md
gold_digger/api_server/api_server.py
gold_digger/managers/exchange_rate_manager.py
tests/test_exchange_rate_manager.py

https://roihunter.atlassian.net/browse/RH-34768
I am quite sad to realize that I already did this before when I introduced /rates API to return exchange rates for each date for the purpose of usage in Fishy which never happened. 😅 I suppose we could remove it. What do you think? @martinvy 

RH-34768: Intervals API

---

gold_digger/data_providers/__init__.py
gold_digger/data_providers/currency_layer.py
gold_digger/data_providers/fixer.py
gold_digger/data_providers/frankfurter.py
gold_digger/data_providers/yahoo.py
gold_digger/di.py
tests/data_providers/conftest.py
tests/data_providers/test_frankfurter.py

https://roihunter.atlassian.net/browse/RH-36296
The new provider has exactly the same API as Fixer, it returns even the same exchange rates, so I reused the Fixer class. I wasn't sure whether we even need such duplicate provider, but I added it anyway.
~I created account in https://exchangeratesapi.io/ and put the access key to Vault & Jenkins.~
Update: After some discussion, I simply replaced the RatesApi provider with Frankfurter provider.
@roihunter/pythonistas please review & merge.

RH-36296: Replace RatesApi provider with Frankfurter provider

---

gold_digger/data_providers/_provider.py
gold_digger/data_providers/currency_layer.py
gold_digger/data_providers/frankfurter.py
gold_digger/data_providers/grandtrunk.py
gold_digger/data_providers/yahoo.py

https://roihunter.atlassian.net/browse/RH-34891
It's a bit messy with each API having a bit different behavior. I considered returning the response from `Provider._get` always, and thus not having to override it for Grandtrunk (and as it is for Frankfurter already), but that would require us to add some additional checks for the status code to all other providers. This way it's probably less code.
@roihunter/pythonistas Please take a look :-)

RH-34891: Use request limit for Grandtrunk

---

kubernetes/gold-digger-api-deployment.yaml
kubernetes/gold-digger-api-hpa.yaml

Updated strategy regarding deployment issues caused by HPA. Also upgraded api version of HPA to `v2` before upgrading kubernetes version from v1.23 to v1.26. Current `autoscaling/v2` [will be deprecated](https://roihunter.atlassian.net/jira/software/c/projects/OPS/boards/10?modal=detail&selectedIssue=OPS-144) in new version.

Updating strategy regarding deployment issues with HPA + HPA API version upgrade

---

jenkins/pipeline/pr-qa-check.groovy

Diff option only shows fixable errors and returns 0 even if unfixable errors are present.

Do not use ruff --diff in PR QA check

---

gold_digger/data_providers/yahoo.py

https://log.roihunter.com/streams/5ebc069546e0fb0012d2f257/search?q=%22yahoo+-+Cannot+get+rate+for+HRK.%22&rangetype=relative&streams=5ebc069546e0fb0012d2f257&from=2592000
Yahoo does not return HRK anymore for a month. Croatia adopted EUR this year.
Btw, I noticed Yahoo returns some exchange rate under different path than we use (we are using
`spark.result.[...].response.[0].indicators.quote.[0].close.[0]`
)
and there values under
`spark.result.[...].response.[0].meta.regularMarketPrice`,
but they seem a bit off sometimes, so I think we can ignore them. See example:
```json
{
"spark": {
"result": [
{
"symbol": "USDHRK=X",
"response": [
{
"meta": {
"currency": "HRK",
"symbol": "USDHRK=X",
"exchangeName": "CCY",
"instrumentType": "CURRENCY",
"firstTradeDate": 1017615600, …
```

Exclude failing HRK currency from Yahoo provider
