- gold_digger/api_server/api_server.py
- gold_digger/data_providers/currency_layer.py
Old currencies (e.g. SKK) may be None from CurrencyLayer provider.
> Handle old currencies

- gold_digger/api_server/api_server.py
Rate req will also update exchange rates from providers if rates are missing.
> Fix: Replace Range req with same start&end date with Rate req

- gold_digger/api_server/api_server.py
- gold_digger/managers/exchange_rate_manager.py
- tests/test_exchange_rate_manager.py
http://is.roihunter.com/issues/8499
I split previous [PR](https://github.com/business-factory/gold-digger/pull/6) to two parts. This is one of them and should be more important. I will decide about destiny of other part later.
@business-factory/pythonistas please R&M.
> Compare rates and try to pick the best

- gold_digger/api_server/api_server.py
Health check will try to get today's exchange rate from USD to USD.
This will check availability of DB and presence of fresh exchange rates in DB.
@Artimi please review & merge
> Health check API endpoint

- gold_digger/config/di.py
- gold_digger/data_providers/__init__.py
- gold_digger/data_providers/google.py
- requirements.txt
http://is.roihunter.com/issues/13481
Ahoj, implementoval jsem nového providera. Myslím si, že víc z toho vymáčknout nešlo, jelikož to API poskytuje pouhý převod na základě aktuálního kurzu :)
> Added new provider for currency conversion - Google

- .gitignore
- gold_digger/config/di.py
- gold_digger/config/params.py
- gold_digger/data_providers/__init__.py
- gold_digger/data_providers/_provider.py
- gold_digger/data_providers/fixer.py
https://business-factory.github.io/docs/tasks/python/fixer-io-currency-provider
> Fixer.io provider

- gold_digger/config/di.py
- gold_digger/data_providers/yahoo.py
- gold_digger/managers/exchange_rate_manager.py
- tests/data_providers/conftest.py
- tests/data_providers/test_yahoo.py
https://is.roihunter.com/issues/18963
> Fix yahoo provider #18963

- Jenkinsfile
Send notification about deploy to Slack and build image if you need it
@business-factory/pythonistas Please review and merge
> Send notification to Slack and build image

- gold_digger/api_server/api_server.py
Unfortunately, DB connection was not check because when requesting exchange rate for USD - USD the result is returned by the application itself, because the rate is always 1.0
> Fix: Check DB connection in health check.

- gold_digger/api_server/api_server.py
- gold_digger/settings/settings_gunicorn.py
The new health check is needed for Kubernetes deployment.
> Simple health check on root url "/" & set timeout for Gunicorn.

- gold_digger/data_providers/yahoo.py
- gold_digger/di.py
https://logs.roihunter.com/messages/graylog2_1339/307f3b10-4233-11e8-a5ec-002590aa2115
> Fix yahoo empty fields in response

- jenkins/pipeline/Jenkinsfile.groovy
- jenkins/pipeline/Multifunctional.groovy
- jenkins/pipeline/_build.groovy
- jenkins/pipeline/_utils.groovy
> Refactor Jenkins scripts

- kubernetes/gold-digger-cron-deployment.yaml
- kubernetes/gold-digger-deployment.yaml
Kubernetes limits added to improve kubernetes scheduler efficiency.
> Kubernetes limits

- gold_digger/data_providers/fixer.py
- gold_digger/data_providers/google.py
- gold_digger/database/dao_exchange_rate.py
- gold_digger/di.py
- gold_digger/managers/exchange_rate_manager.py
- gold_digger/settings/_settings_default.py
- jenkins/pipeline/Multifunctional.groovy
- kubernetes/gold-digger-cron-deployment.yaml
- kubernetes/gold-digger-deployment.yaml
- Fixer now requires access token. I created an account and added credentials to Jenkins & Kube.
- Google blocks us because we do automatic requests. I tried to lower the traffic.
- Yahoo service doesn't work anymore, but I didn't find any new way how to get the rates because the new webpage didn't really work for me when I tried so I am leaving fixing of Yahoo for later.
- I improved some logs and I plan to set up alert with notification to Slack.
> Fix providers & improve logging

- gold_digger/data_providers/fixer.py
If the date is too near the midnight, e.g. 2018-09-05 00:00:02, Fixer considers it as future date and returns error. We should not cache the wrong result and simply try to get supported currencies again later.
> Fix Fixer - get supported currencies

- gold_digger/__main__.py
- gold_digger/di.py
- gold_digger/managers/exchange_rate_manager.py
- tests/test_exchange_rate_manager.py
Downloading from Fixer.io now works fine when downloading from API, but @miso-belica you were right that we should handle also Cron job so I shifted the download time for it by one hour.
@business-factory/pythonistas please take a look & merge.
> Separate Cron update for fixer

- gold_digger/api_server/api_server.py
- kubernetes/gold-digger-cron-deployment.yaml
- kubernetes/gold-digger-deployment.yaml
I removed endpoint `/` and added `/health/alive` along with liveness probe.
@daniilsvirin please review.
> Update Kubernetes configuration

- README.md
- gold_digger/__main__.py
- gold_digger/data_providers/yahoo.py
- gold_digger/di.py
- kubernetes/gold-digger-cron-deployment.yaml
- kubernetes/gold-digger-deployment.yaml
- kubernetes/gold-digger-service.yaml
- tests/data_providers/conftest.py
- tests/data_providers/test_yahoo.py
https://is.roihunter.com/issues/26540
@business-factory/pythonistas
> Fix yahoo provider, #26540

- Dockerfile
- gold_digger/di.py
- gold_digger/settings/settings_gunicorn.py
- gunicorn_logging_master
- kubernetes/gold-digger-cron-deployment.yaml
- kubernetes/gold-digger-deployment.yaml
> Gunicorn logging to graylog

- Dockerfile
- README.md
- gold_digger/__main__.py
- gold_digger/settings/settings_gunicorn.py
> Update gunicorn settings across documentations

- gold_digger/data_providers/__init__.py
- gold_digger/data_providers/_provider.py
- gold_digger/data_providers/fixer.py
- gold_digger/data_providers/unicredit.py
- gold_digger/di.py
https://is.roihunter.com/issues/27540
Added new provider Unicredit.
@business-factory/pythonistas Please review and merge.
> Feature 27540 add unicredit bank as new provider

- gold_digger/__main__.py
- gold_digger/data_providers/__init__.py
- gold_digger/data_providers/_provider.py
- gold_digger/data_providers/currency_layer.py
- gold_digger/data_providers/fixer.py
- gold_digger/data_providers/grandtrunk.py
- gold_digger/data_providers/rates_api.py
- gold_digger/data_providers/yahoo.py
- gold_digger/di.py
- tests/data_providers/conftest.py
- tests/data_providers/test_rates_api.py
https://is.roihunter.com/issues/27945
I added Rates API as new provider for Gold digger. 
Rates are updated only on working days at around 16pm.
> Add Rates API #27945

- gold_digger/data_providers/__init__.py
- gold_digger/data_providers/_provider.py
- gold_digger/data_providers/currency_layer.py
- gold_digger/data_providers/fixer.py
- gold_digger/data_providers/grandtrunk.py
- gold_digger/data_providers/rates_api.py
- gold_digger/data_providers/yahoo.py
- gold_digger/di.py
- tests/data_providers/conftest.py
- tests/data_providers/test_rates_api.py
- [Add Rates API into Gold digger](http://is.roihunter.com/issues/27945)
- Add Rates API #27945 (#63)
> Dev to Master

- Pipfile
- Pipfile.lock
https://is.roihunter.com/issues/28499
https://is.roihunter.com/issues/28543
> Upgdate packages urllib3 and SQLAlchemy #28499 #28543

- README.md
- gold_digger/api_server/api_server.py
- gold_digger/database/dao_exchange_rate.py
- gold_digger/managers/exchange_rate_manager.py
- tests/test_exchange_rate_manager.py
https://is.roihunter.com/issues/28750
> Add new API similar to range, but returning all rates, #28750

- jenkins/pipeline/multifunctional.groovy
https://is.roihunter.com/issues/28714
> Remove dangling images in multifunctional pipeline

- gold_digger/managers/exchange_rate_manager.py
> FIX: log currencies, not tuples from database

- Pipfile
- Pipfile.lock
- setup.cfg
- tests/conftest.py
- tests/database/__init__.py
- tests/database/test_dao.py
Added compatibility for `pytest` 5.0.0
> Bump pytest to 5.0.0

- README.md
- gold_digger/settings/_settings_default.py
- tests/conftest.py
I can see a warning when running tests.
> Fix: Dialect in database URL

- .coafile
- .coafile_without_fails
- .yamllint
- Pipfile
- Pipfile.lock
- bears/GitBear.py
- bears/PyPrintBear.py
- bears/PySortImportsBear.py
- gold_digger/__main__.py
- gold_digger/api_server/api_server.py
- gold_digger/data_providers/fixer.py
- gold_digger/data_providers/grandtrunk.py
- gold_digger/database/dao_exchange_rate.py
- gold_digger/database/db_model.py
- gold_digger/di.py
- gold_digger/managers/exchange_rate_manager.py
- gold_digger/settings/__init__.py
- gold_digger/settings/_settings_default.py
- gold_digger/settings/_settings_master.py
- gold_digger/settings/settings_gunicorn.py
- jenkins/pipeline/_github.groovy
- jenkins/pipeline/_utils.groovy
- jenkins/pipeline/coala.groovy
- jenkins/pipeline/deploy-master.groovy
- tests/conftest.py
- tests/data_providers/test_rates_api.py
- tests/data_providers/test_yahoo.py
- tests/database/conftest.py
- tests/test_exchange_rate_manager.py
I didn't add coala bear for docstrings, because it would require a lot more changes. :-)
> Formatting, unifications, coala, automatic release

- gold_digger/__main__.py
> FIX: Cron health check only once per hour

- jenkins/pipeline/_github.groovy
- jenkins/pipeline/deploy-master.groovy
> Migrate to new helpers URL

- Pipfile
- Pipfile.lock
- gold_digger/di.py
https://roihunter.atlassian.net/browse/RH-30891
@harpener please review & merge.
> RH-30891: Use custom graypy.

- kubernetes/gold-digger-cron-deployment.yaml
- kubernetes/gold-digger-deployment.yaml
https://roihunter.atlassian.net/browse/RH-32193
> RH-32193: Update Kubernetes deployment due to deprecation.

- kubernetes/gold-digger-deployment.yaml
https://roihunter.atlassian.net/browse/RH-32441
@roihunter/pythonistas PRM
> RH-32441:  Improve Kubernetes zero downtime

- jenkins/pipeline/deploy-master.groovy
https://roihunter.atlassian.net/browse/RH-32433
I tested the command with the kubeconfig and it works.
@roihunter/pythonistas PRM :-)
> RH-32433: Add check for Kubernetes deploy

- gold_digger/di.py
- gold_digger/settings/_settings_default.py
- jenkins/pipeline/multifunctional.groovy
https://roihunter.atlassian.net/browse/RH-32787
Vault is ready.
> RH-32787: Use only new Graylog

- gold_digger/api_server/api_server.py
> Unique request_func

- gold_digger/data_providers/yahoo.py
- gold_digger/utils/helpers.py
https://roihunter.atlassian.net/browse/RH-34112
> RH-34112: Limit symbols per request for Yahoo

- gold_digger/api_server/api_server.py
https://roihunter.atlassian.net/browse/RH-34914
> RH-34914: Rename response field

- gold_digger/di.py
- gold_digger/settings/_settings_default.py
- jenkins/pipeline/deploy-master.groovy
- kubernetes/gold-digger-api-deployment.yaml
- kubernetes/gold-digger-cron-deployment.yaml
https://roihunter.atlassian.net/browse/RH-35309
> RH-35309: Add app version to logs from API

- jenkins/pipeline/_github.groovy
- jenkins/pipeline/_utils.groovy
- jenkins/pipeline/deploy-master.groovy
- jenkins/pipeline/multifunctional.groovy
https://roihunter.atlassian.net/browse/RH-30599
> RH-30599: Automatic release

- .github/dependabot.yml
- requirements.txt
https://roihunter.atlassian.net/browse/RH-35592
> RH-35592: Native Github Dependabot

- jenkins/pipeline/_github.groovy
https://roihunter.atlassian.net/browse/RH-35587
> RH-35587: Change Coala check user

- gold_digger/data_providers/_provider.py
- gold_digger/data_providers/currency_layer.py
- gold_digger/data_providers/fixer.py
- gold_digger/data_providers/frankfurter.py
- gold_digger/data_providers/yahoo.py
- gold_digger/di.py
- gold_digger/settings/_settings_default.py
- tests/conftest.py
- tests/data_providers/conftest.py
- tests/data_providers/test_frankfurter.py
- tests/data_providers/test_yahoo.py
https://roihunter.atlassian.net/browse/RH-36769
Yahoo provider started blocking certain User-Agents, including default User-Agent of requests library.
@roihunter/pythonistas please review & merge 🙂
> RH-36769: Specify User-Agent for HTTP requests

- requirements.txt
https://github.blog/2021-09-01-improving-git-protocol-security-github/
> Install graypy using git+https

- jenkins/pipeline/deploy-master.groovy
- jenkins/pipeline/multifunctional.groovy
- jenkins/pipeline/pr-qa-check.groovy
https://roihunter.atlassian.net/browse/RH-38634
@roihunter/pythonistas please check it 🙏
> RH-38634: replace always with cleanup in jenkis pipes

- jenkins/pipeline/deploy-master.groovy
- jenkins/pipeline/multifunctional.groovy
- jenkins/pipeline/pr-qa-check.groovy
https://roihunter.atlassian.net/browse/RH-38956
The current user is not able to delete files created from inside the Docker container when the workspaces is mounted, because the user inside the container is root and the user outside the container is jenkins. Using the same user is a safety precaution.
> RH-38956: Improve Jenkins cleanup

- jenkins/pipeline/deploy-master.groovy
- jenkins/pipeline/multifunctional.groovy
- jenkins/pipeline/pr-qa-check.groovy
https://roihunter.atlassian.net/browse/RH-39379
> fix for jenkins warning

- README.md
- pyproject.toml
> Update Python version in README

- requirements-dev.txt
- setup.cfg
We decided on this a long time ago.
> Remove pytest-cov

- jenkins/pipeline/deploy-master.groovy
The pipeline failed on timeout twice in a row now.
> Increase rollout status timeout to 10m

- kubernetes/gold-digger-api-deployment.yaml
- kubernetes/gold-digger-api-hpa.yaml
https://roihunter.slack.com/archives/C8PCB9STU/p1670249571926779?thread_ts=1670247720.327739&cid=C8PCB9STU
> adding HPA

- jenkins/pipeline/deploy-master.groovy
- jenkins/pipeline/multifunctional.groovy
- jenkins/pipeline/pr-qa-check.groovy
https://roihunter.atlassian.net/browse/RH-41890
> RH-41890: Enable timestamps in Jenkins pipelines

- requirements.txt
https://github.com/pypa/pip/issues/11567
https://discuss.python.org/t/killing-off-the-egg-fragment-once-and-for-all/21660
> Resolve deprecated egg fragment in requirements

- gold_digger/__main__.py
- ruff.toml
Same improvements as in Fishy. :-)
> Ruff improvements

- Dockerfile
- README.md
https://www.python.org/downloads/release/python-31011/
> Bump Python to 3.10.11
